/**
 * DIEPS Intent Engine — Risk Advisor
 * Generates natural-language risk advice and structured risk summaries
 * from risk guardian checks using the OpenRouter LLM.
 */

import { OPENROUTER_API_KEY, OPENROUTER_MODEL_CANDIDATES, OPENROUTER_BASE_URL } from '../../config/index.js';
import { logger } from '../../utils/logger.js';
import type { RiskCheck, RouteNode } from '../../types/index.js';

// ─── Types ─────────────────────────────────────────────────────

export interface RiskSummaryResult {
  /** 3-5 sentence plain-English overview written as DIEPS Agent */
  summary: string;
  /** Structured breakdown with exact numbers and recommendations (no raw threshold data) */
  detailedAnalysis: string;
  /** Overall risk level derived from checks */
  riskLevel: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  /** Whether any check is DANGER */
  hasHighRisk: boolean;
  /** UI Labels generated by LLM for the frontend to display */
  uiLabels?: {
    slippageLabel: string;
    slippageSubLabel: string;
    distributionLabel: string;
    distributionSubLabel: string;
    poolsLabel: string;
    poolsSubLabel: string;
    category: string;
  };
}

// ─── Shared LLM caller ────────────────────────────────────────

async function callOpenRouter(
  model: string,
  systemPrompt: string,
  userMsg: string,
  temperature: number,
  maxTokens: number
): Promise<string> {
  const res = await fetch(`${OPENROUTER_BASE_URL}/chat/completions`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${OPENROUTER_API_KEY}`,
      'HTTP-Referer': 'https://dieps-intent-engine.app',
      'X-Title': 'DIEPS Intent Engine',
    },
    body: JSON.stringify({
      model,
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userMsg },
      ],
      temperature,
      max_tokens: maxTokens,
    }),
  });

  if (!res.ok) {
    const errText = await res.text();
    throw new Error(`OpenRouter API error ${res.status}: ${errText}`);
  }

  const data = await res.json();
  const text: string | undefined = data.choices?.[0]?.message?.content?.trim();
  if (!text) throw new Error('Empty response from LLM');
  return text;
}

// ─── Risk Summary (dual output: summary + detailedAnalysis) ───

function computeRiskLevel(checks: RiskCheck[]): 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL' {
  let score = 100;
  for (const c of checks) {
    if (c.status === 'DANGER') score -= 25;
    else if (c.status === 'WARNING') score -= 10;
  }
  if (score >= 80) return 'LOW';
  if (score >= 60) return 'MEDIUM';
  if (score >= 30) return 'HIGH';
  return 'CRITICAL';
}

/**
 * Build a fallback risk summary from raw check data without any LLM call.
 * Used when all LLM models are unavailable.
 */
function buildFallbackSummary(
  guardianChecks: RiskCheck[],
  sourceToken: string,
  destToken: string,
  amount: string
): RiskSummaryResult {
  const dangerChecks = guardianChecks.filter((c) => c.status === 'DANGER');
  const warnChecks = guardianChecks.filter((c) => c.status === 'WARNING');
  const riskLevel = computeRiskLevel(guardianChecks);

  let summary: string;
  if (dangerChecks.length > 0) {
    const plural = dangerChecks.length > 1 ? 's' : '';
    summary =
      `Your ${amount} ${sourceToken} → ${destToken} swap has ${dangerChecks.length} critical issue${plural}. ` +
      dangerChecks.map((c) => c.message).join(' ') +
      ` DIEPS Agent recommends reducing your trade size or choosing a different pair.`;
  } else if (warnChecks.length > 0) {
    summary =
      `A few factors need your attention for this ${amount} ${sourceToken} → ${destToken} swap. ` +
      warnChecks.map((c) => c.message).join(' ') +
      ` DIEPS Agent says: proceed with awareness.`;
  } else {
    summary =
      `DIEPS Agent checked your ${amount} ${sourceToken} → ${destToken} swap across all risk categories — everything looks healthy. No concerns detected.`;
  }

  const CATEGORY_MAP: Record<string, string> = {
    'High Slippage': 'Slippage',
    'Stale Pools': 'Pool Health',
    'Concentration': 'Concentration',
    'Token Safety': 'Token Safety',
  };

  const detailedLines = guardianChecks.map((c) => {
    const statusIcon = c.status === 'DANGER' ? '[!]' : c.status === 'WARNING' ? '[~]' : c.status === 'SAFE' ? '[ok]' : '[--]';
    const category = CATEGORY_MAP[c.category || ''] || c.category || c.name;
    return `${statusIcon} [${category}] ${c.message}`;
  });

  return {
    summary,
    detailedAnalysis: detailedLines.length > 0
      ? detailedLines.join('\n')
      : 'No issues detected. All checks passed.',
    riskLevel,
    hasHighRisk: dangerChecks.length > 0,
    uiLabels: {
      slippageLabel: dangerChecks.some(c => c.category === 'High Slippage') ? 'High Slippage' : warnChecks.some(c => c.category === 'High Slippage') ? 'Slippage Warning' : 'Safe Slippage',
      slippageSubLabel: dangerChecks.some(c => c.category === 'High Slippage') ? 'Critical price impact.' : warnChecks.some(c => c.category === 'High Slippage') ? 'Moderate price impact.' : 'Within safe parameters.',
      distributionLabel: dangerChecks.some(c => c.name.includes('Concentration')) ? 'Unsafe Token' : warnChecks.some(c => c.name.includes('Concentration')) ? 'Concentrated' : 'Concentration',
      distributionSubLabel: dangerChecks.some(c => c.name.includes('Concentration')) ? 'Critical concentration.' : warnChecks.some(c => c.name.includes('Concentration')) ? 'High concentration.' : 'Low concentration risk.',
      poolsLabel: dangerChecks.length > 0 ? 'High Risk' : warnChecks.length > 0 ? 'Warning' : 'Healthy Liquidity',
      poolsSubLabel: dangerChecks.length > 0 ? 'Critical issues found.' : warnChecks.length > 0 ? 'Proceed with caution.' : 'All pools have deep on-chain reserves.',
      category: dangerChecks.length > 0 ? 'Danger' : warnChecks.length > 0 ? 'Warning' : 'Safe',
    },
  };
}

/**
 * Generate a structured risk summary with both a quick overview and a
 * detailed breakdown. Tries each LLM candidate in order; falls back
 * to raw check data if all models fail.
 */
export async function generateRiskSummary(
  sourceToken: string,
  destToken: string,
  amount: string,
  guardianChecks: RiskCheck[],
  routeNodes: RouteNode[]
): Promise<RiskSummaryResult> {
  if (guardianChecks.length === 0) {
    return {
      summary: `DIEPS Agent ran a full analysis on your ${amount} ${sourceToken} → ${destToken} swap. No risk factors detected — this swap looks clean.`,
      detailedAnalysis: 'No issues detected. All checks passed.',
      riskLevel: 'LOW',
      hasHighRisk: false,
      uiLabels: {
        slippageLabel: 'Safe Slippage',
        slippageSubLabel: 'Within safe parameters.',
        distributionLabel: 'Concentration',
        distributionSubLabel: 'Low concentration risk.',
        poolsLabel: 'Healthy Liquidity',
        poolsSubLabel: 'All pools have deep on-chain reserves.',
        category: 'Safe',
      },
    };
  }

  if (!OPENROUTER_API_KEY) {
    return buildFallbackSummary(guardianChecks, sourceToken, destToken, amount);
  }

  const systemPrompt =
    `You are DIEPS Agent, an intelligent DeFi safety analyst on the Sui blockchain. ` +
    `The user is about to swap ${amount} ${sourceToken} for ${destToken}.\n\n` +
    `Your job: translate raw on-chain risk data into clear, specific, actionable advice ` +
    `so the user can make an informed decision before signing a transaction.\n\n` +
    `You will receive a list of risk checks, each with a name, status (SAFE/WARNING/DANGER), ` +
    `a message, and numeric values. You will also receive route hop data.\n\n` +
    `Analyze ALL risk data and return a JSON object with exactly THREE fields:\n\n` +
    `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n` +
    `1. "summary" — 3 to 4 concise sentences of plain English.\n\n` +
    `Structure:\n` +
    `• CRITICAL REQUIREMENT: Your summary MUST explicitly include the exact phrases "high slippage", "concentration", and "stale pools" when describing the risks or safety of the swap.\n` +
    `• Keep it short, direct, and easy to understand. Combine categories into a single sentence if they are all safe.\n` +
    `• Example: "Your trade has a safe price impact with no high slippage. Token concentration is low, and all liquidity pools are active (no stale pools)."\n` +
    `• Final sentence: A verdict in ONE of these three forms:\n` +
    `  - Low risk:   "DIEPS Agent sees no concerns with this swap."\n` +
    `  - Med risk:   "DIEPS Agent recommends proceeding with awareness of the factors above."\n` +
    `  - High risk:  "DIEPS Agent advises against this swap — the risks outweigh the benefits."\n\n` +
    `Style rules:\n` +
    `• Write like a knowledgeable friend explaining over coffee — not a legal document.\n` +
    `• Use "you" and "your trade" — talk directly to the user.\n` +
    `• Reference specific numbers when they help the user decide.\n` +
    `• Never use the word "threshold". Instead say things like: ` +
    `"your trade uses 12% of available pool liquidity — on the high side" ` +
    `or "the pool last traded 5 days ago — limited recent activity".\n` +
    `• Keep it concise. No fluff. Every sentence should inform or advise.\n\n` +
    `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n` +
    `2. "detailedAnalysis" — a structured breakdown grouped under EXACTLY 4 headers:\n\n` +
    `  [Slippage]\n` +
    `  [Concentration]\n` +
    `  [Pool Health]\n` +
    `  [Token Safety]\n\n` +
    `Map the risk checks to these categories:\n` +
    `• [Slippage] ← Price Impact, Liquidity Risk, Liquidity Depth, Liquidity Health\n` +
    `• [Concentration] ← Supply Concentration, Holder Distribution\n` +
    `• [Pool Health] ← Pool Age Activity\n` +
    `• [Token Safety] ← Token Whitelist, DEX Verification, On-Chain Verification, Pool Verification\n\n` +
    `For each check:\n` +
    `• Write 1-2 plain-language sentences with the exact numbers.\n` +
    `• Explain what the number MEANS for the user, not just what it IS. ` +
    `Good: "Price impact of 0.12% — well within normal range for a trade this size." ` +
    `Bad: "Price impact is 0.12%."\n` +
    `• For SAFE checks: write a brief positive note ` +
    `("All pools are active — the most recent transaction was 2 hours ago.").\n` +
    `• For WARNING/DANGER checks: explain the risk AND suggest what the user can do ` +
    `("Consider splitting this into smaller orders or choosing a pool with deeper liquidity.").\n` +
    `• End each category section with a one-line takeaway when relevant.\n` +
    `• If all checks in a category are safe, write one short sentence confirming it.\n\n` +
    `Never use the word "threshold". Use natural language instead.\n\n` +
    `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n` +
    `3. "uiLabels" — an object containing exactly 7 short strings for the UI cards:\n` +
    `  - "slippageLabel": A short 2-3 word title for the Slippage section (e.g. "Safe Slippage", "High Slippage", "Slippage Warning").\n` +
    `  - "slippageSubLabel": A 1-sentence plain-English description of the slippage risk.\n` +
    `  - "distributionLabel": A short title for the Token Distribution section (e.g. "Concentration", "Unsafe Token").\n` +
    `  - "distributionSubLabel": A 1-sentence plain-English description of token holder concentration.\n` +
    `  - "poolsLabel": A short 2-3 word title for the Liquidity & Pools section (e.g. "Healthy Liquidity", "Unverified DEX", "Low Liquidity", "Stale Pool").\n` +
    `  - "poolsSubLabel": A 1-sentence plain-English description (e.g. "All pools have deep on-chain reserves.", "Route includes unverified DEXes.", "Pools too small for this trade size.").\n` +
    `  - "category": A single word summarizing the overall severity: "Safe", "Warning", or "Danger".\n\n` +
    `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n` +
    `Return ONLY valid JSON. No markdown fences, no explanation, no extra text.`;

  const userMsg =
    `Risk checks:\n${JSON.stringify(guardianChecks.map((c) => ({
      name: c.name,
      status: c.status,
      message: c.message,
      value: c.value,
      threshold: c.threshold,
      category: c.category,
    })), null, 2)}\n\n` +
    `Route hops:\n${JSON.stringify(routeNodes.map((n) => ({
      dex: n.dex,
      ratio: n.ratio,
      fee: n.fee,
      liquidityUsd: n.liquidityUsd,
    })), null, 2)}\n\n` +
    `Trade: ${amount} ${sourceToken} → ${destToken}`;

  for (const model of OPENROUTER_MODEL_CANDIDATES) {
    try {
      const raw = await callOpenRouter(model, systemPrompt, userMsg, 0.2, 1200);

      // Strip markdown code fences if present
      const cleaned = raw.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/i, '').trim();
      const parsed = JSON.parse(cleaned);

      if (parsed.summary && parsed.detailedAnalysis) {
        // LLM may return detailedAnalysis as a structured object instead of a
        // flat string. Convert it to readable text so the frontend can display it.
        let detailedText: string;
        if (typeof parsed.detailedAnalysis === 'string') {
          detailedText = parsed.detailedAnalysis;
        } else if (typeof parsed.detailedAnalysis === 'object' && parsed.detailedAnalysis !== null) {
          // Format category-keyed objects: { "Slippage": "...", "Concentration": "..." }
          detailedText = Object.entries(parsed.detailedAnalysis)
            .map(([key, val]) => `[${key}]\n${typeof val === 'string' ? val : JSON.stringify(val, null, 2)}`)
            .join('\n\n');
        } else {
          detailedText = String(parsed.detailedAnalysis);
        }

        return {
          summary: parsed.summary,
          detailedAnalysis: detailedText,
          riskLevel: computeRiskLevel(guardianChecks),
          hasHighRisk: guardianChecks.some((c) => c.status === 'DANGER'),
          uiLabels: parsed.uiLabels || {
            slippageLabel: 'Safe Slippage',
            slippageSubLabel: 'Within safe parameters.',
            distributionLabel: 'Concentration',
            distributionSubLabel: 'Low concentration risk.',
            poolsLabel: 'Liquidity & Pools',
            poolsSubLabel: 'Analysis completed.',
            category: 'Neutral'
          }
        };
      }
      throw new Error('Missing required fields in LLM response');
    } catch (err: any) {
      logger.warn('Risk summary model failed, trying next candidate', {
        model,
        error: err.message,
      });
    }
  }

  // All models exhausted — use raw fallback
  return buildFallbackSummary(guardianChecks, sourceToken, destToken, amount);
}

// ─── Legacy: Short risk advice (1-2 sentences) ────────────────

export async function summarizeRiskAdvice(
  sourceToken: string,
  destToken: string,
  risks: RiskCheck[]
): Promise<string> {
  if (risks.length === 0) {
    return '';
  }

  const fallbackMessage = "⚠️ High Risk Detected: " + risks.map(r => r.message).join(' ');

  if (!OPENROUTER_API_KEY) {
    return fallbackMessage;
  }

  const systemPrompt =
    `You are a DeFi security advisor on the Sui blockchain. The user is about to swap ${sourceToken} for ${destToken}. ` +
    `The system has detected some high-risk warnings (e.g. high slippage, concentration, or stale pools). ` +
    `Write exactly 1-2 short, professional, and friendly sentences in English to advise the user about these risks. ` +
    `Do not use markdown formatting. Be concise and helpful, emphasizing caution.`;

  const userMsg = `Risks detected: ${JSON.stringify(risks.map(r => ({ risk: r.name, detail: r.message })))}`;

  for (const model of OPENROUTER_MODEL_CANDIDATES) {
    try {
      const text = await callOpenRouter(model, systemPrompt, userMsg, 0.3, 150);
      return `⚠️ ${text}`;
    } catch (err: any) {
      logger.warn('Risk advice model failed, trying next candidate', {
        model,
        error: err.message,
      });
    }
  }

  return fallbackMessage;
}
